const trainSchedule = [
  {
    id: 1,
    StartStation: "ColomboFort",
    Arrival_StartStation: "05:55:00",
    Departure_Time: "05:55:00",
    Arrival_Destination: "08:46:00",
    Destination: "Kandy",
    EndStation: "Badulla",
    Arrival_EndStation: "16:07:00",
    Train_Type: "EXPRESS TRAIN",
    Train_Name: "Podi Menike",
    Train_Number: "1005",
    Run_By: "Daily",
    Available_Classes: ["First Class", "Second Class", "Third Class"],
  },

  {
    id: 1,
    StartStation: "ColomboFort",
    Arrival_StartStation: "07:00:00",
    Departure_Time: "07:00:00",
    Arrival_Destination: "09:38:00",
    Destination: "Kandy",
    EndStation: "Kandy",
    Arrival_EndStation: "16:07:00",
    Train_Type: "A.C. - INTERCITY",
    Train_Name: "1009",
    Train_Number: "1009",
    Run_By: "DAILY",
    Available_Classes: ["First Class", "Second Class", "Third Class"],
  },

  {
    id: 1,
    StartStation: "ColomboFort",
    Arrival_StartStation: "07:05:00",
    Departure_Time: "07:05:00",
    Arrival_Destination: "09:38:00",
    Destination: "Kandy",
    EndStation: "Kandy",
    Arrival_EndStation: "16:07:00",
    Train_Type: "INTERCITY",
    Train_Name: "1009",
    Train_Number: "1009",
    Run_By: "DAILY",
    Available_Classes: ["First Class", "Second Class", "Third Class"],
  },

  {
    id: 1,
    StartStation: "ColomboFort",
    Arrival_StartStation: "07:05:00",
    Departure_Time: "07:05:00",
    Arrival_Destination: "09:38:00",
    Destination: "Kandy",
    EndStation: "Kandy",
    Arrival_EndStation: "16:07:00",
    Train_Type: "INTERCITY",
    Train_Name: "1009",
    Train_Number: "1009",
    Run_By: "DAILY",
    Available_Classes: ["First Class", "Second Class", "Third Class"],
  },

];
export default trainSchedule;
